spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: //email
    password: //password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

kafka:
  auto-offset-reset: latest
  bootstrap-servers: localhost:9092
  group-id: pms
  topic:
    name: ping

server:
  port: 8082
