#kafka:
#  auto-offset-reset: latest
#  bootstrap-servers: localhost:9092
#  group-id: pms
#  topic:
#    name: ping
#server:
#  port: 8082










kafka:
  auto-offset-reset: latest
  bootstrap-servers: localhost:9092
  group-id: test-group-id
  topic:
    name: test-topic
server:
  port: 8082
