spring:
  application:
    name: Auth-server
  security:
    user:
      name: root
      password: $2a$12$PQNfG.gixwclFQeJ.drED.0ttQWiI7QUiyQL/tyb/ar9TMk2v2EwO
  datasource:
    url: jdbc:postgresql://localhost:5555/ping
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

jwt:
  secret: H2A6xN9zQk!w@4JfPp7Rx*UeM0nY#LdZp

logging:
  level:
    com:
      codify: DEBUG
    org:
      springframework:
        security: DEBUG
