server:
  port: 8081
spring:
  application:
    name: ping-my-server

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: ping

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      hostname: localhost


#
#server:
#  port: 8081
#spring:
#  application:
#    name: kafka-producer
#
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      topic: test-topic
